name: mobile_programming
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.17.0 # library for internalization
  shared_preferences: ^2.0.5 # For storing data in local storage.
  flutter_mobx: ^2.0.0 # for state management and this provides the Observer.
  provider: ^5.0.0 # for state management
  carousel_slider: ^4.0.0
  mobx: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.2 #provides a concrete way of generating files using Dart code, outside of tools
  mobx_codegen: ^2.0.1+3 #for auto generating code for stores.
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/demo.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
